### ISSUE TITLE
Clarify testing plans

### ISSUE THREAD

**Issue by palemieux** [w3c/charter-timed-text#11]
Clarify the specific requirements for the following, or remove:

_Testing plans for each specification, starting from the earliest drafts._

What is the "earliest draft"?

What is a testing plan?

**Comment by tmichel07** [comment]
This statement comes from the W3C Charter Template.
https://w3c.github.io/charter-drafts/charter-template.html

Therefore, I am not sure I can remove it

So let's discuss it during our call

Thierry

**Comment by nigelmegitt** [comment]
I agree, this text is unclear. I don't think we're compelled to incorporate everything in the charter template. However I think the intent here is probably a good one, and as a matter of working process I would like to encourage the group to provide tests alongside new features as part of the specification work, so that we are all very clear about the behaviour that we are specifying.

**Comment by nigelmegitt** [comment]
[taken up by TTWG today] Add a "should" so:

> A testing plan should be associated with each specification, starting from the earliest draft.

**Comment by tmichel07** [comment]
Previous statement replaced with
A testing plan should be associated with each specification, starting from the earliest draft.

**Comment by nigelmegitt** [comment]
There's an extraneous full stop/period at the end of the sentence, happy for that to be mopped up in an editorial/proofreading pass later. Closing as this addresses the issue as agreed by the WG.
