### ISSUE TITLE
Shorten horizontal review period

### ISSUE THREAD

**Issue by palemieux** [w3c/charter-timed-text#28]
The proposed charter states: _Invitation for review must be issued during each major standards-track document transition, including FPWD and at least 3 months before CR_

The mandatory 3-month review period means that a W3C group can wait 90 days before filing issues against a WD, after which additional time will be required to resolve the issues. This seems excessive in cases where changes are limited in scope, and especially since the review is performed by other W3C groups that are not burdened by the need to communicate through liaison. It is also not clear how this mandatory period works when CR is the first step, as with Edited and Amended Recommendations.

Recommend modifying text to:

_Invitation for review should be issued during each major standards-track document transition, including FPWD and CR, and should be issued when major changes occur in a specification. The time period between FPWD and CR, if such a time period exists, should be no less than 1 month to provide adequate time for review._

... or reverting it to that of the current charter:

_Invitation for review should be issued during each major standards-track document transition, including FPWD and CR, and should be issued when major changes occur in a specification._

In fact, it is not clear why this change was made in the first place.

**Comment by nigelmegitt** [comment]
Looks like this came from the draft charter template. I also did not notice it before. I don't think it would generally cause us much difficulty since I don't _think_ any TTWG specs went from (FP)WD to CR in less than three months (I haven't checked). It would be nice to have the option to go quicker.

I don't know if this 3 months period is being imposed by W3C to ensure HR can go ahead or if it's just an example of "typical practice". @plehegar perhaps you can answer?

Looking at the wording carefully, I do not believe that it means the WG must actively seek review for a minor WD update, nor that the minimum period between a small WD update and CR must be 3 months. Also I think there is still discretion for the WG to decide what is a "major" transition, so I'm not too concerned about this. 

From a practical perspective I think the only real result of this clause is to say that we are not saying that we expect HR on a completely new spec in less than 3 months before going to CR.

**Comment by plehegar** [comment]
This comes from https://github.com/w3c/charter-drafts/pull/110 and isn't a requirement from the Process. Looks like this came from i18n concerns (but couldn't locate the exact charter impacted). My recommendation would be to drop this sentence altogether. I do not think the charter template should push for this extra requirement.

**Comment by plehegar** [comment]
@r12a @iherman comments?

**Comment by iherman** [comment]
@plehegar (the reason I am pinged is, I presume, because another WG charter is getting to its end right now, namely JSON-LD), I am not bothered by the overall sentence being in the charter, the feedback I got (for other charters) is that H. reviews would like to see at least this in the charter (actually, I believe it came from WAI concerns, not I18N). I would however, agree with @palemieux that the explicit 3 month in the charter would make more harm than good in some cases...

**Comment by r12a** [comment]
Last year and the year before we had a spate of groups asking for i18n review with literally only a week or two to go before they planned to move to CR. It caused major disruption to the i18n schedule as we scrambled to accomodate them, and was problematic for them because we still weren't able to always meet their schedule. Groups were also faced with making significant changes to their specs, which it would have been better to know about much earlier. Reviews were rushed, and caused frustration on both sides.

Before a group goes to CR it needs to allow sufficient time for the HR group to find time to schedule the review work while juggling other groups and priorities, and then actually conduct a review, but in particular the schedule needs to also accomodate sufficient time for the group developing the spec to properly discuss and understand the comments,  take advice and decisions about how to change the spec, and incorporate those changes. 

When we had a Last Call phases, we used to always have problems because groups (1) left it to the last minute, and (2) considered their work done by that time and no longer had the energy to make substantial changes. Now we don't have that phase, we are trying to ensure that groups get review comments early enough to avoid problems.

We estimate that for an average spec you want to send a call for review _at least_ 3 months before it expects to transition to CR. (You'll be well aware that discussions lasted much longer than that for the TTML2 spec.) Hope that helps clarify the rationale.

**Comment by palemieux** [comment]
> We estimate that for an average spec you want to send a call for review at least 3 months before it expects to transition to CR. 

@r12a What about the case where none of the changes in the document are i18n-related? Will the i18n group require 3 months to reach the conclusion that no review is needed?

> but in particular the schedule needs to also accomodate sufficient time to properly discuss and understand the comments, t

Does the 3 month include the back and forth, or is the time needed for the i18n group to conduct its initial review?

**Comment by r12a** [comment]
> @r12a What about the case where none of the changes in the document are i18n-related? Will the i18n group require 3 months to reach the conclusion that no review is needed?

Note that i said 'for an average spec'. However, that said, it's not hard to come up with examples of specs where the group developing the spec assumed there were no HR related aspects, but in fact there were. That can (and has) come as a nasty shock when it comes to light just before the planned move to CR.

> Does the 3 month include the back and forth, or is the time needed for the i18n group to conduct its initial review?

The former. Btw, I updated my previous comment to say: "in particular the schedule needs to also accomodate sufficient time **for the group developing the spec** to properly discuss and understand the comments, take advice and decisions about how to change the spec, and incorporate those changes."

**Comment by aphillips** [comment]
I'm going to pile on here: very often teams make the assumption that I18N has nothing to say about their spec, when, in fact, we do. I don't think it's helpful for us to insist on long review periods at the CR transition. That's not at all what I18N is interested in doing. Instead, what @r12a is suggesting is that WGs approach us early/earlier in the spec development cycle so that there is no need for a "fire drill" at the end.

I18N does not need 90 days to perform a review, but we also cannot respond instantly--the WG process requires at least one teleconference to discuss issues (otherwise it's just me or Richard or whomever sending comments) and at least one to tell the team about it. That makes our minimum review period roughly 2 weeks. More time is better--we often have more than one thing going on at the same time.

If we do find comments, you'll, of course, need time to respond to them and possibly to discuss with us. So realistically, you'll probably want 4-6 weeks, which is 1/2 of the 90 days. If a WG has been proactive as @r12a and I suggested above, you won't need any of this time (as our review work will already be done). 

I would:

* ask WGs to perform the self-review at roughly FPWD so that the WG has considered common I18N issues already
* ensure that a formal review request is sent to horizontal review WGs at least 6 weeks prior to CR transition
* ask WGs to pencil in a time at least 90 days prior to CR for horizontal review *not because the review takes that long but because that's the best "last milestone" time to do it*
* recommend that WGs announce their work to horizontal review WGs at FPWD (assuming that is more than 90 days prior to CR), even if a formal review wouldn't be appropriate at that time

**Comment by palemieux** [comment]
In light of the discussion above, I recommend reverting to the text from the previous charter: _Invitation for review should be issued during each major standards-track document transition, including FPWD and CR, and should be issued when major changes occur in a specification._ This allows flexibility in managing horizontal review.

**Comment by nigelmegitt** [comment]
Looking at the comments by @r12a and @aphillips , which make complete sense, I do not get the feeling that the intent is to set a minimum period between FPWD and CR, rather it is to ensure that review is commenced as early as possible for the least inconvenience to both the reviewers and the WG. The 90 days is a _should_ therefore, not a minimum-time-elapsed in the style of a patent exclusion claim deadline.

If it is important to put a reference to the 90 days in, then this needs to be clarified, because the current wording is a _must_. At the least we should insert a should, so the smallest change to the current wording to resolve this would be:

> Invitation for review must be issued during each major standards-track document transition, including FPWD and **should be issued** at least 3 months before CR

where I've added the words "should be issued". I'd also accept:

* an additional sentence requiring initial review to be completed by the reviewing group within 6 weeks of the request being made. 
* a requirement that CR transition must not be made until the review is complete and all issues are either resolved or deferred until a later version of the specification with agreement from the reviewing group.

This seems to me to capture the intent and the practice and ensure all interests are met. 

I'm not sure if we can actually require of another group that their initial review is completed in max 6 weeks, in a WG Charter, but it's worth a go...

The only remaining unknown for me is _who decides_ when a specification change is major. In the light of the comments it seems that only the reviewing group can assess if the change is significant in their particular context, though I would think that most WGs have a pretty good idea already. I'd support a "review light" that says something along the lines of "Here are the changes we're making; do you agree that it will not impact [e.g. i18n] and that a review is not needed?"
